### PR TITLE
chore: inline engine strict

### PR DESCRIPTION
**Pull request by evenstensberg**
A little less config files is a good thing.

### CODE REVIEW

**Comment by camargo** [comment]
Hi @evenstensberg, it seems [engineStrict](https://docs.npmjs.com/cli/v6/configuring-npm/package-json?v=true#enginestrict) is deprecated and the `.npmrc` file is the preferred way to do this.

**Comment by evenstensberg** [comment]
Alright 👍🏽

**Comment by evenstensberg** [comment]
Maybe specifying node and npm versions in package.json too, is good?

**Comment by camargo** [comment]
@evenstensberg Yes I think eventually. This repo is very much a prototype. But please keep an eye on it! If we start adding issues I'll mark them as good first ones if you'd like to contribute!

**Comment by evenstensberg** [comment]
Awesome. Yes please label! 👍🏾

**Pull request closed without merging**
